//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MagusTools.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MagusTools.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ügyesség.
        /// </summary>
        internal static string ATTR_Agility {
            get {
                return ResourceManager.GetString("ATTR_Agility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asztrál.
        /// </summary>
        internal static string ATTR_Astral {
            get {
                return ResourceManager.GetString("ATTR_Astral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Szépség.
        /// </summary>
        internal static string ATTR_Charisma {
            get {
                return ResourceManager.GetString("ATTR_Charisma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Állóképesség.
        /// </summary>
        internal static string ATTR_Endurance {
            get {
                return ResourceManager.GetString("ATTR_Endurance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Életerő.
        /// </summary>
        internal static string ATTR_Health {
            get {
                return ResourceManager.GetString("ATTR_Health", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intelligencia.
        /// </summary>
        internal static string ATTR_Intelligence {
            get {
                return ResourceManager.GetString("ATTR_Intelligence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Érzékelés.
        /// </summary>
        internal static string ATTR_Perception {
            get {
                return ResourceManager.GetString("ATTR_Perception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gyorsaság.
        /// </summary>
        internal static string ATTR_Speed {
            get {
                return ResourceManager.GetString("ATTR_Speed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erő.
        /// </summary>
        internal static string ATTR_Strength {
            get {
                return ResourceManager.GetString("ATTR_Strength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Akaraterő.
        /// </summary>
        internal static string ATTR_Willpower {
            get {
                return ResourceManager.GetString("ATTR_Willpower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KAP költség.
        /// </summary>
        internal static string MISC_PrimaryAttributes_SpentCCP {
            get {
                return ResourceManager.GetString("MISC_PrimaryAttributes_SpentCCP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Átlag.
        /// </summary>
        internal static string MISC_Text_AbilityAverage {
            get {
                return ResourceManager.GetString("MISC_Text_AbilityAverage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktuális.
        /// </summary>
        internal static string MISC_Text_Actual {
            get {
                return ResourceManager.GetString("MISC_Text_Actual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alap.
        /// </summary>
        internal static string MISC_Text_Base {
            get {
                return ResourceManager.GetString("MISC_Text_Base", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KAP.
        /// </summary>
        internal static string MISC_Text_CCP {
            get {
                return ResourceManager.GetString("MISC_Text_CCP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Karakter.
        /// </summary>
        internal static string MM_Character {
            get {
                return ResourceManager.GetString("MM_Character", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mentés szövegfájlba.
        /// </summary>
        internal static string MM_Character_ExportAsText {
            get {
                return ResourceManager.GetString("MM_Character_ExportAsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generálás.
        /// </summary>
        internal static string MM_Character_Generate {
            get {
                return ResourceManager.GetString("MM_Character_Generate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fájl.
        /// </summary>
        internal static string MM_File {
            get {
                return ResourceManager.GetString("MM_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Új.
        /// </summary>
        internal static string MM_File_New {
            get {
                return ResourceManager.GetString("MM_File_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nem-Játékos Karakter (NJK).
        /// </summary>
        internal static string MM_File_New_NPC {
            get {
                return ResourceManager.GetString("MM_File_New_NPC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Játékos Karakter (JK).
        /// </summary>
        internal static string MM_File_New_PC {
            get {
                return ResourceManager.GetString("MM_File_New_PC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Megnyitás.
        /// </summary>
        internal static string MM_File_Open {
            get {
                return ResourceManager.GetString("MM_File_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kilépés.
        /// </summary>
        internal static string MM_File_Quit {
            get {
                return ResourceManager.GetString("MM_File_Quit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mentés.
        /// </summary>
        internal static string MM_File_Save {
            get {
                return ResourceManager.GetString("MM_File_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mentés másként...
        /// </summary>
        internal static string MM_File_SaveAs {
            get {
                return ResourceManager.GetString("MM_File_SaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Segítség.
        /// </summary>
        internal static string MM_Help {
            get {
                return ResourceManager.GetString("MM_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MagusTools névjegye.
        /// </summary>
        internal static string MM_Help_About {
            get {
                return ResourceManager.GetString("MM_Help_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Segítség megtekintése.
        /// </summary>
        internal static string MM_Help_ViewHelp {
            get {
                return ResourceManager.GetString("MM_Help_ViewHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beállítások.
        /// </summary>
        internal static string MM_Options {
            get {
                return ResourceManager.GetString("MM_Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nyelvek.
        /// </summary>
        internal static string MM_Options_Language {
            get {
                return ResourceManager.GetString("MM_Options_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speciális.
        /// </summary>
        internal static string MM_Options_Specials {
            get {
                return ResourceManager.GetString("MM_Options_Specials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kiegészítők.
        /// </summary>
        internal static string MM_Options_Tools {
            get {
                return ResourceManager.GetString("MM_Options_Tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kockadobó.
        /// </summary>
        internal static string MM_Options_Tools_Diceroller {
            get {
                return ResourceManager.GetString("MM_Options_Tools_Diceroller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fegyverraktár.
        /// </summary>
        internal static string TAB_Armory {
            get {
                return ResourceManager.GetString("TAB_Armory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alapinformációk.
        /// </summary>
        internal static string TAB_BasicInfo {
            get {
                return ResourceManager.GetString("TAB_BasicInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elosztható KAP.
        /// </summary>
        internal static string TAB_BasicInfo_AvailableCCPLabel {
            get {
                return ResourceManager.GetString("TAB_BasicInfo_AvailableCCPLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kor.
        /// </summary>
        internal static string TAB_BasicInfo_CharAgeLabel {
            get {
                return ResourceManager.GetString("TAB_BasicInfo_CharAgeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Szülőföld.
        /// </summary>
        internal static string TAB_BasicInfo_CharBirthplaceLabel {
            get {
                return ResourceManager.GetString("TAB_BasicInfo_CharBirthplaceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jellem.
        /// </summary>
        internal static string TAB_BasicInfo_CharCharacteristicLabel {
            get {
                return ResourceManager.GetString("TAB_BasicInfo_CharCharacteristicLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kaszt.
        /// </summary>
        internal static string TAB_BasicInfo_CharClassLabel {
            get {
                return ResourceManager.GetString("TAB_BasicInfo_CharClassLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nem.
        /// </summary>
        internal static string TAB_BasicInfo_CharGenderLabel {
            get {
                return ResourceManager.GetString("TAB_BasicInfo_CharGenderLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Szint.
        /// </summary>
        internal static string TAB_BasicInfo_CharLevelLabel {
            get {
                return ResourceManager.GetString("TAB_BasicInfo_CharLevelLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string TAB_BasicInfo_CharNameLabel {
            get {
                return ResourceManager.GetString("TAB_BasicInfo_CharNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faj.
        /// </summary>
        internal static string TAB_BasicInfo_CharRaceLabel {
            get {
                return ResourceManager.GetString("TAB_BasicInfo_CharRaceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Szférák.
        /// </summary>
        internal static string TAB_BasicInfo_CharRealmsLabel {
            get {
                return ResourceManager.GetString("TAB_BasicInfo_CharRealmsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vallás.
        /// </summary>
        internal static string TAB_BasicInfo_CharReligionLabel {
            get {
                return ResourceManager.GetString("TAB_BasicInfo_CharReligionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Felszerelés.
        /// </summary>
        internal static string TAB_Equipment {
            get {
                return ResourceManager.GetString("TAB_Equipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elsődleges Képességek.
        /// </summary>
        internal static string TAB_PrimaryAttributes {
            get {
                return ResourceManager.GetString("TAB_PrimaryAttributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Másodlagos Képességek.
        /// </summary>
        internal static string TAB_SecondaryAttributes {
            get {
                return ResourceManager.GetString("TAB_SecondaryAttributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Képzettségek.
        /// </summary>
        internal static string TAB_Skills {
            get {
                return ResourceManager.GetString("TAB_Skills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Áttekintés.
        /// </summary>
        internal static string TAB_Summary {
            get {
                return ResourceManager.GetString("TAB_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MagusTools Karakterszerkesztő.
        /// </summary>
        internal static string TITLE {
            get {
                return ResourceManager.GetString("TITLE", resourceCulture);
            }
        }
    }
}
