//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MagusTools.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MagusTools.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agility.
        /// </summary>
        internal static string ATTR_Agility {
            get {
                return ResourceManager.GetString("ATTR_Agility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Astral.
        /// </summary>
        internal static string ATTR_Astral {
            get {
                return ResourceManager.GetString("ATTR_Astral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charisma.
        /// </summary>
        internal static string ATTR_Charisma {
            get {
                return ResourceManager.GetString("ATTR_Charisma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endurance.
        /// </summary>
        internal static string ATTR_Endurance {
            get {
                return ResourceManager.GetString("ATTR_Endurance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Health.
        /// </summary>
        internal static string ATTR_Health {
            get {
                return ResourceManager.GetString("ATTR_Health", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intelligence.
        /// </summary>
        internal static string ATTR_Intelligence {
            get {
                return ResourceManager.GetString("ATTR_Intelligence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perception.
        /// </summary>
        internal static string ATTR_Perception {
            get {
                return ResourceManager.GetString("ATTR_Perception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speed.
        /// </summary>
        internal static string ATTR_Speed {
            get {
                return ResourceManager.GetString("ATTR_Speed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strength.
        /// </summary>
        internal static string ATTR_Strength {
            get {
                return ResourceManager.GetString("ATTR_Strength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Willpower.
        /// </summary>
        internal static string ATTR_Willpower {
            get {
                return ResourceManager.GetString("ATTR_Willpower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chaos.
        /// </summary>
        internal static string CHAR_Characteristic_Chaos {
            get {
                return ResourceManager.GetString("CHAR_Characteristic_Chaos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chaos - Death.
        /// </summary>
        internal static string CHAR_Characteristic_ChaosDeath {
            get {
                return ResourceManager.GetString("CHAR_Characteristic_ChaosDeath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chaos - Life.
        /// </summary>
        internal static string CHAR_Characteristic_ChaosLife {
            get {
                return ResourceManager.GetString("CHAR_Characteristic_ChaosLife", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Death.
        /// </summary>
        internal static string CHAR_Characteristic_Death {
            get {
                return ResourceManager.GetString("CHAR_Characteristic_Death", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Death - Chaos.
        /// </summary>
        internal static string CHAR_Characteristic_DeathChaos {
            get {
                return ResourceManager.GetString("CHAR_Characteristic_DeathChaos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Death - Order.
        /// </summary>
        internal static string CHAR_Characteristic_DeathOrder {
            get {
                return ResourceManager.GetString("CHAR_Characteristic_DeathOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Life.
        /// </summary>
        internal static string CHAR_Characteristic_Life {
            get {
                return ResourceManager.GetString("CHAR_Characteristic_Life", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Life - Chaos.
        /// </summary>
        internal static string CHAR_Characteristic_LifeChaos {
            get {
                return ResourceManager.GetString("CHAR_Characteristic_LifeChaos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Life - Order.
        /// </summary>
        internal static string CHAR_Characteristic_LifeOrder {
            get {
                return ResourceManager.GetString("CHAR_Characteristic_LifeOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order.
        /// </summary>
        internal static string CHAR_Characteristic_Order {
            get {
                return ResourceManager.GetString("CHAR_Characteristic_Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order - Death.
        /// </summary>
        internal static string CHAR_Characteristic_OrderDeath {
            get {
                return ResourceManager.GetString("CHAR_Characteristic_OrderDeath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order - Life.
        /// </summary>
        internal static string CHAR_Characteristic_OrderLife {
            get {
                return ResourceManager.GetString("CHAR_Characteristic_OrderLife", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female.
        /// </summary>
        internal static string CHAR_Gender_Female {
            get {
                return ResourceManager.GetString("CHAR_Gender_Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male.
        /// </summary>
        internal static string CHAR_Gender_Male {
            get {
                return ResourceManager.GetString("CHAR_Gender_Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        internal static string CHAR_Gender_Other {
            get {
                return ResourceManager.GetString("CHAR_Gender_Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dwarf.
        /// </summary>
        internal static string CHAR_Race_Dwarf {
            get {
                return ResourceManager.GetString("CHAR_Race_Dwarf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elf.
        /// </summary>
        internal static string CHAR_Race_Elf {
            get {
                return ResourceManager.GetString("CHAR_Race_Elf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Half-Elf.
        /// </summary>
        internal static string CHAR_Race_HalfElf {
            get {
                return ResourceManager.GetString("CHAR_Race_HalfElf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Human.
        /// </summary>
        internal static string CHAR_Race_Human {
            get {
                return ResourceManager.GetString("CHAR_Race_Human", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sublimated Orc.
        /// </summary>
        internal static string CHAR_Race_SublimatedOrc {
            get {
                return ResourceManager.GetString("CHAR_Race_SublimatedOrc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gnome.
        /// </summary>
        internal static string CHAT_Race_Gnome {
            get {
                return ResourceManager.GetString("CHAT_Race_Gnome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goblin.
        /// </summary>
        internal static string CHAT_Race_Goblin {
            get {
                return ResourceManager.GetString("CHAT_Race_Goblin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ability average.
        /// </summary>
        internal static string MISC_Text_AbilityAverage {
            get {
                return ResourceManager.GetString("MISC_Text_AbilityAverage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actual.
        /// </summary>
        internal static string MISC_Text_Actual {
            get {
                return ResourceManager.GetString("MISC_Text_Actual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base.
        /// </summary>
        internal static string MISC_Text_Base {
            get {
                return ResourceManager.GetString("MISC_Text_Base", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CCP.
        /// </summary>
        internal static string MISC_Text_CCP {
            get {
                return ResourceManager.GetString("MISC_Text_CCP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Character.
        /// </summary>
        internal static string MM_Character {
            get {
                return ResourceManager.GetString("MM_Character", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export As Text.
        /// </summary>
        internal static string MM_Character_ExportAsText {
            get {
                return ResourceManager.GetString("MM_Character_ExportAsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate.
        /// </summary>
        internal static string MM_Character_Generate {
            get {
                return ResourceManager.GetString("MM_Character_Generate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string MM_File {
            get {
                return ResourceManager.GetString("MM_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        internal static string MM_File_New {
            get {
                return ResourceManager.GetString("MM_File_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non-Playable Character (NPC).
        /// </summary>
        internal static string MM_File_New_NPC {
            get {
                return ResourceManager.GetString("MM_File_New_NPC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playable Character (PC).
        /// </summary>
        internal static string MM_File_New_PC {
            get {
                return ResourceManager.GetString("MM_File_New_PC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        internal static string MM_File_Open {
            get {
                return ResourceManager.GetString("MM_File_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quit.
        /// </summary>
        internal static string MM_File_Quit {
            get {
                return ResourceManager.GetString("MM_File_Quit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string MM_File_Save {
            get {
                return ResourceManager.GetString("MM_File_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save As....
        /// </summary>
        internal static string MM_File_SaveAs {
            get {
                return ResourceManager.GetString("MM_File_SaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string MM_Help {
            get {
                return ResourceManager.GetString("MM_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About MagusTools.
        /// </summary>
        internal static string MM_Help_About {
            get {
                return ResourceManager.GetString("MM_Help_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Help.
        /// </summary>
        internal static string MM_Help_ViewHelp {
            get {
                return ResourceManager.GetString("MM_Help_ViewHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        internal static string MM_Options {
            get {
                return ResourceManager.GetString("MM_Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string MM_Options_Language {
            get {
                return ResourceManager.GetString("MM_Options_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string MM_Options_Settings {
            get {
                return ResourceManager.GetString("MM_Options_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools.
        /// </summary>
        internal static string MM_Options_Tools {
            get {
                return ResourceManager.GetString("MM_Options_Tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diceroller.
        /// </summary>
        internal static string MM_Options_Tools_Diceroller {
            get {
                return ResourceManager.GetString("MM_Options_Tools_Diceroller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Armory.
        /// </summary>
        internal static string TAB_Armory {
            get {
                return ResourceManager.GetString("TAB_Armory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic Information.
        /// </summary>
        internal static string TAB_BasicInfo {
            get {
                return ResourceManager.GetString("TAB_BasicInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equipment.
        /// </summary>
        internal static string TAB_Equipment {
            get {
                return ResourceManager.GetString("TAB_Equipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary Attributes.
        /// </summary>
        internal static string TAB_PrimaryAttributes {
            get {
                return ResourceManager.GetString("TAB_PrimaryAttributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secondary Attributes.
        /// </summary>
        internal static string TAB_SecondaryAttributes {
            get {
                return ResourceManager.GetString("TAB_SecondaryAttributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skills.
        /// </summary>
        internal static string TAB_Skills {
            get {
                return ResourceManager.GetString("TAB_Skills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary.
        /// </summary>
        internal static string TAB_Summary {
            get {
                return ResourceManager.GetString("TAB_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MagusTools Character Editor.
        /// </summary>
        internal static string TITLE {
            get {
                return ResourceManager.GetString("TITLE", resourceCulture);
            }
        }
    }
}
