//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MagusTools.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MagusTools.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agility.
        /// </summary>
        internal static string ATTR_Agility {
            get {
                return ResourceManager.GetString("ATTR_Agility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aim.
        /// </summary>
        internal static string ATTR_Aim {
            get {
                return ResourceManager.GetString("ATTR_Aim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Astral.
        /// </summary>
        internal static string ATTR_Astral {
            get {
                return ResourceManager.GetString("ATTR_Astral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attack.
        /// </summary>
        internal static string ATTR_Attack {
            get {
                return ResourceManager.GetString("ATTR_Attack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charisma.
        /// </summary>
        internal static string ATTR_Charisma {
            get {
                return ResourceManager.GetString("ATTR_Charisma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CM / Level.
        /// </summary>
        internal static string ATTR_CMperLevel {
            get {
                return ResourceManager.GetString("ATTR_CMperLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defense.
        /// </summary>
        internal static string ATTR_Defense {
            get {
                return ResourceManager.GetString("ATTR_Defense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endurance.
        /// </summary>
        internal static string ATTR_Endurance {
            get {
                return ResourceManager.GetString("ATTR_Endurance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Health.
        /// </summary>
        internal static string ATTR_Health {
            get {
                return ResourceManager.GetString("ATTR_Health", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HP.
        /// </summary>
        internal static string ATTR_HP {
            get {
                return ResourceManager.GetString("ATTR_HP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initiative.
        /// </summary>
        internal static string ATTR_Initiative {
            get {
                return ResourceManager.GetString("ATTR_Initiative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intelligence.
        /// </summary>
        internal static string ATTR_Intelligence {
            get {
                return ResourceManager.GetString("ATTR_Intelligence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KP.
        /// </summary>
        internal static string ATTR_KP {
            get {
                return ResourceManager.GetString("ATTR_KP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KP / Level.
        /// </summary>
        internal static string ATTR_KPperLevel {
            get {
                return ResourceManager.GetString("ATTR_KPperLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perception.
        /// </summary>
        internal static string ATTR_Perception {
            get {
                return ResourceManager.GetString("ATTR_Perception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PR.
        /// </summary>
        internal static string ATTR_PR {
            get {
                return ResourceManager.GetString("ATTR_PR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PR / Level.
        /// </summary>
        internal static string ATTR_PRperLevel {
            get {
                return ResourceManager.GetString("ATTR_PRperLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speed.
        /// </summary>
        internal static string ATTR_Speed {
            get {
                return ResourceManager.GetString("ATTR_Speed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strength.
        /// </summary>
        internal static string ATTR_Strength {
            get {
                return ResourceManager.GetString("ATTR_Strength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Willpower.
        /// </summary>
        internal static string ATTR_Willpower {
            get {
                return ResourceManager.GetString("ATTR_Willpower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lv/%.
        /// </summary>
        internal static string GRID_Level {
            get {
                return ResourceManager.GetString("GRID_Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        internal static string GRID_Price {
            get {
                return ResourceManager.GetString("GRID_Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skill name.
        /// </summary>
        internal static string GRID_SkillName {
            get {
                return ResourceManager.GetString("GRID_SkillName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CM.
        /// </summary>
        internal static string MISC_SecondaryAttributes_Text_SpentCM {
            get {
                return ResourceManager.GetString("MISC_SecondaryAttributes_Text_SpentCM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average.
        /// </summary>
        internal static string MISC_Text_AbilityAverage {
            get {
                return ResourceManager.GetString("MISC_Text_AbilityAverage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actual.
        /// </summary>
        internal static string MISC_Text_Actual {
            get {
                return ResourceManager.GetString("MISC_Text_Actual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CCP.
        /// </summary>
        internal static string MISC_Text_CCP {
            get {
                return ResourceManager.GetString("MISC_Text_CCP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remaining.
        /// </summary>
        internal static string MISC_Text_Remaining {
            get {
                return ResourceManager.GetString("MISC_Text_Remaining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spent CCP.
        /// </summary>
        internal static string MISC_Text_TotalSpentCCPOnTab {
            get {
                return ResourceManager.GetString("MISC_Text_TotalSpentCCPOnTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Character.
        /// </summary>
        internal static string MM_Character {
            get {
                return ResourceManager.GetString("MM_Character", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export as text.
        /// </summary>
        internal static string MM_Character_ExportAsText {
            get {
                return ResourceManager.GetString("MM_Character_ExportAsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate.
        /// </summary>
        internal static string MM_Character_Generate {
            get {
                return ResourceManager.GetString("MM_Character_Generate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string MM_File {
            get {
                return ResourceManager.GetString("MM_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New character.
        /// </summary>
        internal static string MM_File_New {
            get {
                return ResourceManager.GetString("MM_File_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        internal static string MM_File_Open {
            get {
                return ResourceManager.GetString("MM_File_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quit.
        /// </summary>
        internal static string MM_File_Quit {
            get {
                return ResourceManager.GetString("MM_File_Quit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string MM_File_Save {
            get {
                return ResourceManager.GetString("MM_File_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save as...
        /// </summary>
        internal static string MM_File_SaveAs {
            get {
                return ResourceManager.GetString("MM_File_SaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string MM_Help {
            get {
                return ResourceManager.GetString("MM_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About MagusTools.
        /// </summary>
        internal static string MM_Help_About {
            get {
                return ResourceManager.GetString("MM_Help_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View help.
        /// </summary>
        internal static string MM_Help_ViewHelp {
            get {
                return ResourceManager.GetString("MM_Help_ViewHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        internal static string MM_Options {
            get {
                return ResourceManager.GetString("MM_Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Languages.
        /// </summary>
        internal static string MM_Options_Language {
            get {
                return ResourceManager.GetString("MM_Options_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specials.
        /// </summary>
        internal static string MM_Options_Specials {
            get {
                return ResourceManager.GetString("MM_Options_Specials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools.
        /// </summary>
        internal static string MM_Options_Tools {
            get {
                return ResourceManager.GetString("MM_Options_Tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diceroller.
        /// </summary>
        internal static string MM_Options_Tools_Diceroller {
            get {
                return ResourceManager.GetString("MM_Options_Tools_Diceroller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Armory.
        /// </summary>
        internal static string TAB_Armory {
            get {
                return ResourceManager.GetString("TAB_Armory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic Information.
        /// </summary>
        internal static string TAB_BasicInfo {
            get {
                return ResourceManager.GetString("TAB_BasicInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AMR.
        /// </summary>
        internal static string TAB_BasicInfo_AMRLabel {
            get {
                return ResourceManager.GetString("TAB_BasicInfo_AMRLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available CCP.
        /// </summary>
        internal static string TAB_BasicInfo_AvailableCCPLabel {
            get {
                return ResourceManager.GetString("TAB_BasicInfo_AvailableCCPLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age.
        /// </summary>
        internal static string TAB_BasicInfo_CharAgeLabel {
            get {
                return ResourceManager.GetString("TAB_BasicInfo_CharAgeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alignment.
        /// </summary>
        internal static string TAB_BasicInfo_CharAlignmentLabel {
            get {
                return ResourceManager.GetString("TAB_BasicInfo_CharAlignmentLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birthplace.
        /// </summary>
        internal static string TAB_BasicInfo_CharBirthplaceLabel {
            get {
                return ResourceManager.GetString("TAB_BasicInfo_CharBirthplaceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class.
        /// </summary>
        internal static string TAB_BasicInfo_CharClassLabel {
            get {
                return ResourceManager.GetString("TAB_BasicInfo_CharClassLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        internal static string TAB_BasicInfo_CharGenderLabel {
            get {
                return ResourceManager.GetString("TAB_BasicInfo_CharGenderLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level.
        /// </summary>
        internal static string TAB_BasicInfo_CharLevelLabel {
            get {
                return ResourceManager.GetString("TAB_BasicInfo_CharLevelLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string TAB_BasicInfo_CharNameLabel {
            get {
                return ResourceManager.GetString("TAB_BasicInfo_CharNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Race.
        /// </summary>
        internal static string TAB_BasicInfo_CharRaceLabel {
            get {
                return ResourceManager.GetString("TAB_BasicInfo_CharRaceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Realms.
        /// </summary>
        internal static string TAB_BasicInfo_CharRealmsLabel {
            get {
                return ResourceManager.GetString("TAB_BasicInfo_CharRealmsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Religion.
        /// </summary>
        internal static string TAB_BasicInfo_CharReligionLabel {
            get {
                return ResourceManager.GetString("TAB_BasicInfo_CharReligionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Damagebonus.
        /// </summary>
        internal static string TAB_BasicInfo_DamageBonusLabel {
            get {
                return ResourceManager.GetString("TAB_BasicInfo_DamageBonusLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MMR.
        /// </summary>
        internal static string TAB_BasicInfo_MMRLabel {
            get {
                return ResourceManager.GetString("TAB_BasicInfo_MMRLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mana.
        /// </summary>
        internal static string TAB_BasicInfo_MPLabel {
            get {
                return ResourceManager.GetString("TAB_BasicInfo_MPLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mana / Level.
        /// </summary>
        internal static string TAB_BasicInfo_MPperLevelLabel {
            get {
                return ResourceManager.GetString("TAB_BasicInfo_MPperLevelLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other stats.
        /// </summary>
        internal static string TAB_BasicInfo_OtherStatsLabel {
            get {
                return ResourceManager.GetString("TAB_BasicInfo_OtherStatsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Psy.
        /// </summary>
        internal static string TAB_BasicInfo_PSYLabel {
            get {
                return ResourceManager.GetString("TAB_BasicInfo_PSYLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Psy / Level.
        /// </summary>
        internal static string TAB_BasicInfo_PSYperLevelLabel {
            get {
                return ResourceManager.GetString("TAB_BasicInfo_PSYperLevelLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equipment.
        /// </summary>
        internal static string TAB_Equipment {
            get {
                return ResourceManager.GetString("TAB_Equipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary Attributes.
        /// </summary>
        internal static string TAB_PrimaryAttributes {
            get {
                return ResourceManager.GetString("TAB_PrimaryAttributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secondary Attributes.
        /// </summary>
        internal static string TAB_SecondaryAttributes {
            get {
                return ResourceManager.GetString("TAB_SecondaryAttributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skills.
        /// </summary>
        internal static string TAB_Skills {
            get {
                return ResourceManager.GetString("TAB_Skills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available Skills.
        /// </summary>
        internal static string TAB_Skills_AvailableSkillsLabel {
            get {
                return ResourceManager.GetString("TAB_Skills_AvailableSkillsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Drag the chosen skills to the right side to learn them..
        /// </summary>
        internal static string TAB_Skills_Hint_A {
            get {
                return ResourceManager.GetString("TAB_Skills_Hint_A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Learned skills can be edited with a double-click and you can delete the selected ones with the Delete button..
        /// </summary>
        internal static string TAB_Skills_Hint_B {
            get {
                return ResourceManager.GetString("TAB_Skills_Hint_B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected Skills.
        /// </summary>
        internal static string TAB_Skills_SelectedSkillsLabel {
            get {
                return ResourceManager.GetString("TAB_Skills_SelectedSkillsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary.
        /// </summary>
        internal static string TAB_Summary {
            get {
                return ResourceManager.GetString("TAB_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MagusTools Character Generator.
        /// </summary>
        internal static string TITLE {
            get {
                return ResourceManager.GetString("TITLE", resourceCulture);
            }
        }
    }
}
